# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jatrigueros/programas/RALine/osggis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jatrigueros/programas/RALine/osggis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jatrigueros/programas/RALine/osggis/CMakeFiles /home/jatrigueros/programas/RALine/osggis/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jatrigueros/programas/RALine/osggis/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named osgGIS

# Build rule for target.
osgGIS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgGIS
.PHONY : osgGIS

# fast build rule for target.
osgGIS/fast:
	$(MAKE) -f src/osgGIS/CMakeFiles/osgGIS.dir/build.make src/osgGIS/CMakeFiles/osgGIS.dir/build
.PHONY : osgGIS/fast

#=============================================================================
# Target rules for targets named osgGISProjects

# Build rule for target.
osgGISProjects: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgGISProjects
.PHONY : osgGISProjects

# fast build rule for target.
osgGISProjects/fast:
	$(MAKE) -f src/osgGISProjects/CMakeFiles/osgGISProjects.dir/build.make src/osgGISProjects/CMakeFiles/osgGISProjects.dir/build
.PHONY : osgGISProjects/fast

#=============================================================================
# Target rules for targets named app_osggis_build

# Build rule for target.
app_osggis_build: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_osggis_build
.PHONY : app_osggis_build

# fast build rule for target.
app_osggis_build/fast:
	$(MAKE) -f src/osggis_build/CMakeFiles/app_osggis_build.dir/build.make src/osggis_build/CMakeFiles/app_osggis_build.dir/build
.PHONY : app_osggis_build/fast

#=============================================================================
# Target rules for targets named app_osggis_makelayer

# Build rule for target.
app_osggis_makelayer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_osggis_makelayer
.PHONY : app_osggis_makelayer

# fast build rule for target.
app_osggis_makelayer/fast:
	$(MAKE) -f src/osggis_makelayer/CMakeFiles/app_osggis_makelayer.dir/build.make src/osggis_makelayer/CMakeFiles/app_osggis_makelayer.dir/build
.PHONY : app_osggis_makelayer/fast

#=============================================================================
# Target rules for targets named app_osggis_simple

# Build rule for target.
app_osggis_simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_osggis_simple
.PHONY : app_osggis_simple

# fast build rule for target.
app_osggis_simple/fast:
	$(MAKE) -f src/osggis_simple/CMakeFiles/app_osggis_simple.dir/build.make src/osggis_simple/CMakeFiles/app_osggis_simple.dir/build
.PHONY : app_osggis_simple/fast

#=============================================================================
# Target rules for targets named app_osggis_viewer

# Build rule for target.
app_osggis_viewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_osggis_viewer
.PHONY : app_osggis_viewer

# fast build rule for target.
app_osggis_viewer/fast:
	$(MAKE) -f src/osggis_viewer/CMakeFiles/app_osggis_viewer.dir/build.make src/osggis_viewer/CMakeFiles/app_osggis_viewer.dir/build
.PHONY : app_osggis_viewer/fast

#=============================================================================
# Target rules for targets named app_osggis_mapper

# Build rule for target.
app_osggis_mapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_osggis_mapper
.PHONY : app_osggis_mapper

# fast build rule for target.
app_osggis_mapper/fast:
	$(MAKE) -f src/osggis_mapper/CMakeFiles/app_osggis_mapper.dir/build.make src/osggis_mapper/CMakeFiles/app_osggis_mapper.dir/build
.PHONY : app_osggis_mapper/fast

#=============================================================================
# Target rules for targets named app_osggis_drape

# Build rule for target.
app_osggis_drape: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app_osggis_drape
.PHONY : app_osggis_drape

# fast build rule for target.
app_osggis_drape/fast:
	$(MAKE) -f src/osggis_drape/CMakeFiles/app_osggis_drape.dir/build.make src/osggis_drape/CMakeFiles/app_osggis_drape.dir/build
.PHONY : app_osggis_drape/fast

#=============================================================================
# Target rules for targets named osggis_test_encode

# Build rule for target.
osggis_test_encode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osggis_test_encode
.PHONY : osggis_test_encode

# fast build rule for target.
osggis_test_encode/fast:
	$(MAKE) -f tests/encode/CMakeFiles/osggis_test_encode.dir/build.make tests/encode/CMakeFiles/osggis_test_encode.dir/build
.PHONY : osggis_test_encode/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... osgGIS"
	@echo "... osgGISProjects"
	@echo "... app_osggis_build"
	@echo "... app_osggis_makelayer"
	@echo "... app_osggis_simple"
	@echo "... app_osggis_viewer"
	@echo "... app_osggis_mapper"
	@echo "... app_osggis_drape"
	@echo "... osggis_test_encode"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

